# Generated by Django 5.1.4 on 2024-12-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales_app.customer', verbose_name='الزبون'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقداً'), ('card', 'بطاقة ائتمان'), ('transfer', 'تحويل بنكي'), ('check', 'شيك')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
    ]
