# Generated by Django 5.1.4 on 2024-12-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_payment_customer_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_exempt',
            field=models.BooleanField(default=False, verbose_name='معفى من الضريبة'),
        ),
    ]
