from django.urls import path
from . import views

app_name = 'sales_app'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/add/', views.add_customer, name='add_customer'),
    path('customers/<int:pk>/edit/', views.edit_customer, name='edit_customer'),
    path('customers/<int:pk>/delete/', views.delete_customer, name='delete_customer'),
    path('customers/<int:pk>/', views.customer_detail, name='customer_detail'),
    # path('customers/<int:pk>/account-statement/', views.customer_account_statement, name='customer_account_statement'),
    path('customers/<int:pk>/account-statement/print/', views.customer_account_statement_print, name='customer_account_statement_print'),
    path('invoices/', views.invoice_list, name='invoice_list'),
    path('invoices/create/', views.create_invoice, name='create_invoice'),
    path('invoices/<int:pk>/', views.invoice_detail, name='invoice_detail'),
    path('invoices/<int:pk>/edit/', views.edit_invoice, name='edit_invoice'),
    path('invoices/<int:pk>/delete/', views.delete_invoice, name='delete_invoice'),
    path('invoices/<int:pk>/print/', views.print_invoice, name='print_invoice'),
    path('invoices/<int:invoice_id>/items/add/', views.add_invoice_items, name='add_invoice_items'),
    path('invoices/<int:invoice_id>/payment/add/', views.add_payment, name='add_payment'),
    path('invoices/update-status/<int:pk>/', views.update_invoice_status, name='update_invoice_status'),
    path('invoice/<int:pk>/toggle-payment/', views.toggle_payment_status, name='toggle_payment_status'),
    path('products/', views.product_list, name='product_list'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('products/<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('invoice/get_product_price/<int:product_id>/', views.get_product_price, name='get_product_price'),
    path('payments/', views.payment_list, name='payment_list'),
    path('receivables/', views.receivable_list, name='receivable_list'),
    path('receivables/<int:pk>/', views.receivable_detail, name='receivable_detail'),
    path('receivables/add/', views.add_receivable, name='add_receivable'),
    path('receivables/<int:pk>/edit/', views.edit_receivable, name='edit_receivable'),
    path('receivables/<int:pk>/print/', views.print_receivable, name='print_receivable'),
    path('settings/', views.settings_view, name='settings'),
    path('settings/company/', views.company_info, name='company_info'),
    path('settings/invoice/', views.invoice_settings, name='invoice_settings'),
    path('settings/notifications/', views.notification_settings, name='notification_settings'),
    path('settings/backup/', views.backup_settings, name='backup_settings'),
    path('reports/', views.reports_dashboard, name='reports_dashboard'),
    path('backup/', views.backup_view, name='backup'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/mark-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('reports/', views.report_list, name='report_list'),
    path('inventory-report/', views.inventory_report, name='inventory_report'),
    path('sales-report/', views.sales_report, name='sales_report'),
    path('reports/payment-receipts/', views.payment_receipt_report, name='payment_receipt_report'),
    path('print_payment_receipt/<int:payment_id>/', views.print_payment_receipt, name='print_payment_receipt'),
    path('invoice-items/<int:item_id>/delete/', views.delete_invoice_item, name='delete_invoice_item'),
]
